# =========================
# General Configuration
# =========================
project_name: eeg-sentiment-transformer
random_seed: 42
device: cuda  # or "cpu"

# =========================
# Data Settings
# =========================
data:
  raw_data_dir: data/raw
  processed_data_dir: data/processed
  sentiment_lexicon_path: data/sentiment_lexicons/sentiwords.txt
  batch_size: 32
  num_workers: 4
  input_dim: 128

# =========================
# Model Settings
# =========================
model:
  architecture: SentimentAwareTransformer
  input_dim: 128
  hidden_dim: 256
  num_heads: 4
  num_layers: 2
  num_classes: 6
  dropout: 0.1

# =========================
# Training Settings
# =========================
training:
  epochs: 10
  learning_rate: 0.0001
  optimizer: adam
  loss_function: cross_entropy
  use_edo: true
  checkpoint_dir: checkpoints
  log_file: train.log

# =========================
# Evaluation Settings
# =========================
evaluation:
  model_checkpoint: checkpoints/model_epoch_10.pt
  report_metrics: [accuracy, precision, recall, f1_score]
